[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.mainnet]
program = "F5wQsBbjHAViAimLojNZRCxdecvHnUTfWqKnLCz2Bdho"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/arena-authority.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
